CREATE TABLE IF NOT EXISTS categories(
id SERIAL PRIMARY KEY,
name VARCHAR(24) UNIQUE);

CREATE TABLE IF NOT EXISTS products(
id SERIAL PRIMARY KEY,
title VARCHAR(36),
description VARCHAR(140),
category_id INTEGER,
FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS statuses(
id SERIAL PRIMARY KEY,
name VARCHAR(10) UNIQUE);

CREATE TABLE IF NOT EXISTS users(
id SERIAL PRIMARY KEY,
name VARCHAR(24),
email VARCHAR(24) UNIQUE);

CREATE TABLE IF NOT EXISTS orders(
id SERIAL PRIMARY KEY,
user_id INTEGER,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
status_id INTEGER,
FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS order_items(
id SERIAL PRIMARY KEY,
order_id INTEGER,
FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
product_id INTEGER,
FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE);
