sentense = input()
number_of_spaces = sentense.count(' ')
print('first way:', sentense.replace(' ', '-', number_of_spaces))
value_of_r_spaces = len(sentense) - len(sentense.rstrip(' '))
value_of_l_spaces = len(sentense) - len(sentense.lstrip(' '))
print('-'*value_of_l_spaces + '-'.join(sentense.split()) + '-'*value_of_r_spaces)
